        </main>
        <footer class="fixed-bottom bg-dark text-center">
            <a href="https://github.com/theKindlyMallard/boardgames" target="blank">
                Follow this project on GitHub
                <i class="fab fa-github"></i>
            </a>
            <div id="superClock">
                <span id="clock"></span>
                <i id="startClock" class="fa fa-clock" onclick="startTime()"
                   title="Every time you would like to check the seconds you do not have them turned on in this Windows clock below? No problem! XD"
                   ></i>
            </div>
        </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
        <script src="/public/js/main.js"></script>
    </body>
</html>