<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Boardgames</title>
        <link rel="stylesheet" href="/public/css/style.css" type="text/css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    </head>
    <body>
        <header class="sticky-top bg-dark">
            <nav class="navbar container navbar-expand-lg navbar-dark bg-dark">
                <a id="main-navbar-brand" class="navbar-brand" href="#kk">
                    <img src="/public/img/mallard-icon.png" width="60" height="60" class="d-inline-block" alt="logo">
                    Boardgames
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarToggler">
                    <div class="navbar-nav mr-auto"></div>
                    <ul class="navbar-nav mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/games">Games</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/home/contactUs">Contact us</a>
                        </li>
                        <?php
                        if (\Controller\UserController::isLoggedIn()) {
                        ?>
                        <li class="nav-item">
                            <div id="account-info" class="dropdown nav-link">
                                <span class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                                    Account
                                </span>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="../user/profile">Full Name</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="/user/logout">Sign out</a>
                                </div>
                            </div>
                        </li>
                        <?php
                        } else {
                        ?>
                        <a class="btn btn-outline-light my-2 my-sm-0" href="/user/login">Sign in</a>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
            </nav>
        </header>
        <main class="container">
