<div class="row">
    <div class="col-sm">
        <div class="card">
            <img class="card-img-top" src="/public/img/mallardWallpaper.jpg" alt="the kindly Mallard">
            <div class="card-body">
                <h5 class="card-title">theKindlyMallard</h5>
                <h6 class="card-subtitle mb-2 text-muted">Mallard is a kind of duck.</h6>
                <p class="card-text">Hello. Some questions or advice? Send me a message by contact form!</p>
                <a href="https://github.com/theKindlyMallard" class="card-link">
                    <i class="fab fa-github"></i>
                    GitHub
                </a>
            </div>
        </div>
    </div>
    <div class="col-sm">
        <h2>Contact form</h2>
        <hr>
        <form action="" method="POST" id="<?= Controller\HomeController::FORM_NAME_CONTACT ?>">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="<?= Controller\HomeController::FIELD_NAME ?>">Name</label>
                    <input type="text" class="form-control" 
                           id="<?= Controller\HomeController::FIELD_NAME ?>"
                           name="<?= Controller\HomeController::FIELD_NAME ?>" placeholder="How to call You?">
                </div>
                <div class="form-group col-md-6">
                    <label for="<?= Controller\HomeController::FIELD_EMAIL ?>">E-mail</label>
                    <input type="email" class="form-control" required
                           aria-describedby="emailHelpBlock"
                           id="<?= Controller\HomeController::FIELD_EMAIL ?>"
                           name="<?= Controller\HomeController::FIELD_EMAIL ?>" placeholder="E-mail">
                    <small id="emailHelpBlock" class="form-text text-muted">
                        Let me possibility to contact with You ;)
                    </small>
                </div>
            </div>
            <div class="form-group">
                <label for="<?= Controller\HomeController::FIELD_MESSAGE ?>">Address</label>
                <textarea class="form-control" required
                          id="<?= Controller\HomeController::FIELD_MESSAGE ?>" 
                          name="<?= Controller\HomeController::FIELD_MESSAGE ?>" rows="6">So, what's the message?</textarea>
            </div>
            <hr>
            <button type="submit" class="btn btn-outline-dark btn-lg float-right"
                    name="<?= Controller\HomeController::FORM_NAME_CONTACT ?>">
                Send
            </button>
        </form>
        <?php
        if (!empty($this->messages)) {
            foreach ($this->messages as $type => $message) {
                if ($type == 'ok') {
                    $alertType = 'alert-success';
                } else if ($type == 'error') {
                    $alertType = 'alert-warning';
                } else {
                    $alertType = 'alert-secondary';
                }
                echo '<div class="alert ' . $alertType . '" role="alert">';
                echo $message;
                echo '</div>';
            }
        }
        ?>
    </div>
</div>