<?php
//For now there are just errors possible.
if (!empty($this->messages)) {
    foreach ($this->messages as $message) {
        echo '<div class="alert alert-danger" role="alert">';
        echo $message;
        echo '</div>';
    }
}
?>
<form action="" method="POST" id="<?= Controller\UserController::FORM_NAME_SIGN_IN ?>">
    <div class="form-group">
        <label for="<?= Controller\UserController::FIELD_LOGIN ?>">Login</label>
        <input class="form-control"
               id="<?= Controller\UserController::FIELD_LOGIN ?>"
               name="<?= Controller\UserController::FIELD_LOGIN ?>"
               type="text" placeholder="Enter login" required>
    </div>
    <div class="form-group">
        <label for="<?= Controller\UserController::FIELD_PASSWORD ?>">Password</label>
        <input class="form-control"
               id="<?= Controller\UserController::FIELD_PASSWORD ?>"
               name="<?= Controller\UserController::FIELD_PASSWORD ?>"
               type="password" placeholder="Password" required>
    </div>
    <button type="submit" class="btn btn-primary"
            name="<?= Controller\UserController::FORM_NAME_SIGN_IN ?>">
        Sign in
    </button>
</form>